### PR TITLE
Fix matrix constructors generating identities for the wrong base type

### LINKED ISSUE #523: IdentityRewriteComposite uses wrong type when generating identities for matrix constructors
```
if (i == indexToFurtherTransform) {
  argument = applyIdentityFunction(argument, type.getElementType(), constContext, depth,
     fuzzer);
}
```

BasicType.getElementType() is only used for vectors - it defaults to returning float if you pass a matrix type to it. For matrices, we should use BasicType.getColumnType() instead.

### PR DESCRIPTION
**Pull request by abelbriggs1**
Fixes #523.

### CODE REVIEW

File: generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java [hunk 1]
```diff
@@ -820,8 +820,7 @@ public Expr apply(Expr expr, BasicType type, boolean constContext, int depth,
       // identities to, and ... is the other entries in v that we don't change.
       // Similarly for matrices.
 
-      assert BasicType.allVectorTypes().contains(type)
-          || BasicType.allMatrixTypes().contains(type);
+      assert type.isVector() || type.isMatrix();
```
Comment (afd) [inline generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java]: Nice!

File: generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java [hunk 2]
```diff
@@ -832,8 +831,9 @@ public Expr apply(Expr expr, BasicType type, boolean constContext, int depth,
       for (int i = 0; i < numIndices; i++) {
         Expr argument = new ArrayIndexExpr(expr.clone(), new IntConstantExpr(String.valueOf(i)));
         if (i == indexToFurtherTransform) {
-          argument = applyIdentityFunction(argument, type.getElementType(), constContext, depth,
-              fuzzer);
+          argument = applyIdentityFunction(argument,
+              (type.isVector() ? type.getElementType() : type.getColumnType()),
```
Comment (afd) [inline generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java]: ^ I would remove the parentheses around the ternary, but this is really a matter of taste.
